apiVersion: v1
kind: Service
metadata:
  name: blog-service-lb
spec:
  selector:
    app: blog-lb
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deploy-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-lb
  template:
    metadata:
      labels:
        app: blog-lb #same as line 22
    spec:
      containers:
        - name: blog
          image: philipl1/gl-blog-lb
          ports:
            - containerPort: 8000
